services:
  - type: web
    name: n8n-on-render
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: youradmin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourpassword
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-on-render.onrender.com
